import localFont from "next/font/local";
import { Inter } from "next/font/google";
import Navbar from "./../components/Navbar";
import "./globals.css";
import SessionLayout from "./../components/SessionLayout";

// Google Inter Font
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// Local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionLayout>
          <Navbar />
          {children}
        </SessionLayout>
      </body>
    </html>
  );
}
